# Generated by Django 4.2.15 on 2024-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(default=11111),
        ),
    ]
